version: "3.9"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    build: api
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
    depends_on:
      - db